# Generated by Django 5.2.11 on 2026-03-02 02:12

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20, verbose_name='Symbol')),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop', 'Stop'), ('stop_limit', 'Stop Limit'), ('trailing_stop', 'Trailing Stop')], max_length=20, verbose_name='Order Type')),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=10, verbose_name='Side')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('limit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Limit Price')),
                ('stop_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Stop Price')),
                ('filled_qty', models.IntegerField(default=0, verbose_name='Filled Quantity')),
                ('filled_avg_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Filled Avg Price')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('submitted', 'Submitted'), ('partially_filled', 'Partially Filled'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending', max_length=30, verbose_name='Status')),
                ('broker_order_id', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='Broker Order ID')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Requires Approval')),
                ('approval_requested_at', models.DateTimeField(blank=True, null=True, verbose_name='Approval Requested At')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Approved At')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='Rejection Reason')),
                ('agent_decision_id', models.UUIDField(blank=True, null=True, verbose_name='Agent Decision ID')),
                ('agent_rationale', models.TextField(blank=True, verbose_name='Agent Rationale')),
                ('agent_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Agent Confidence')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted to Broker')),
                ('filled_at', models.DateTimeField(blank=True, null=True, verbose_name='Filled At')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20, verbose_name='Symbol')),
                ('trade_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit'), ('partial_exit', 'Partial Exit')], max_length=20, verbose_name='Trade Type')),
                ('side', models.CharField(max_length=10, verbose_name='Side')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('price', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Price')),
                ('commission', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Commission')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Value')),
                ('realized_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Realized P&L')),
                ('realized_pnl_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Realized P&L %')),
                ('broker_trade_id', models.CharField(blank=True, max_length=255, verbose_name='Broker Trade ID')),
                ('executed_at', models.DateTimeField(db_index=True, verbose_name='Executed At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Trade',
                'verbose_name_plural': 'Trades',
                'db_table': 'trades',
                'ordering': ['-executed_at'],
            },
        ),
    ]
