# Generated by Django 5.2.11 on 2026-03-02 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('portfolios', '0001_initial'),
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='order',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='strategies.strategy'),
        ),
        migrations.AddField(
            model_name='trade',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='orders.order'),
        ),
        migrations.AddField(
            model_name='trade',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='trade',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='portfolios.position'),
        ),
        migrations.AddField(
            model_name='trade',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trades', to='strategies.strategy'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['portfolio', '-created_at'], name='orders_portfol_9aa97d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-created_at'], name='orders_status_f8c8df_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['broker_order_id'], name='orders_broker__a04e54_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['symbol', '-created_at'], name='orders_symbol_eb8eb0_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['portfolio', '-executed_at'], name='trades_portfol_9453b7_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['symbol', '-executed_at'], name='trades_symbol_a56273_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['strategy', '-executed_at'], name='trades_strateg_1368fc_idx'),
        ),
    ]
