# Generated by Django 5.2.11 on 2026-03-03 14:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('orders', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('order_created', 'Order Created'), ('order_submitted', 'Order Submitted'), ('order_filled', 'Order Filled'), ('order_partially_filled', 'Order Partially Filled'), ('order_cancelled', 'Order Cancelled'), ('order_rejected', 'Order Rejected'), ('order_approved', 'Order Approved (HITL)'), ('order_rejected_user', 'Order Rejected by User'), ('trade_executed', 'Trade Executed'), ('trade_settled', 'Trade Settled'), ('position_opened', 'Position Opened'), ('position_closed', 'Position Closed'), ('position_updated', 'Position Updated'), ('portfolio_reconciled', 'Portfolio Reconciled'), ('strategy_activated', 'Strategy Activated'), ('strategy_paused', 'Strategy Paused'), ('strategy_executed', 'Strategy Executed'), ('signal_generated', 'Signal Generated'), ('broker_connected', 'Broker Connected'), ('broker_disconnected', 'Broker Disconnected'), ('broker_error', 'Broker Error'), ('suspicious_activity', 'Suspicious Activity Detected'), ('rate_limit_exceeded', 'Rate Limit Exceeded'), ('unauthorized_access', 'Unauthorized Access Attempt')], db_index=True, max_length=50)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('object_id', models.CharField(max_length=255)),
                ('data_before', models.JSONField(blank=True, null=True)),
                ('data_after', models.JSONField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='audit_logs_user_id_e11c73_idx'), models.Index(fields=['action', '-timestamp'], name='audit_logs_action_f48619_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_logs_content_b0ef47_idx'), models.Index(fields=['-timestamp'], name='audit_logs_timesta_e93820_idx')],
            },
        ),
    ]
