# Generated by Django 5.2.11 on 2026-03-02 02:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('broker', models.CharField(choices=[('alpaca', 'Alpaca'), ('alpaca_paper', 'Alpaca (Paper)'), ('interactive_brokers', 'Interactive Brokers')], max_length=50, verbose_name='Broker')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error')], default='inactive', max_length=20, verbose_name='Status')),
                ('api_key_encrypted', models.TextField(verbose_name='API Key (Encrypted)')),
                ('api_secret_encrypted', models.TextField(blank=True, verbose_name='API Secret (Encrypted)')),
                ('account_number', models.CharField(blank=True, max_length=100, verbose_name='Account Number')),
                ('is_paper_trading', models.BooleanField(default=True, verbose_name='Paper Trading')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Sync')),
                ('last_error', models.TextField(blank=True, verbose_name='Last Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Broker Connection',
                'verbose_name_plural': 'Broker Connections',
                'db_table': 'broker_connections',
                'ordering': ['-created_at'],
            },
        ),
    ]
