# Generated by Django 5.2.11 on 2026-03-02 02:12

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backtest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('initial_capital', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Initial Capital')),
                ('final_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Final Capital')),
                ('total_return', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Total Return %')),
                ('annual_return', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Annual Return %')),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Sharpe Ratio')),
                ('sortino_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Sortino Ratio')),
                ('max_drawdown', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Max Drawdown %')),
                ('total_trades', models.IntegerField(default=0, verbose_name='Total Trades')),
                ('winning_trades', models.IntegerField(default=0, verbose_name='Winning Trades')),
                ('losing_trades', models.IntegerField(default=0, verbose_name='Losing Trades')),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Win Rate %')),
                ('avg_trade_pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Avg Trade P&L')),
                ('results', models.JSONField(blank=True, null=True, verbose_name='Detailed Results')),
                ('equity_curve', models.JSONField(blank=True, null=True, verbose_name='Equity Curve')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
            ],
            options={
                'verbose_name': 'Backtest',
                'verbose_name_plural': 'Backtests',
                'db_table': 'backtests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Strategy Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('strategy_type', models.CharField(choices=[('momentum', 'Momentum Breakout'), ('mean_reversion', 'Mean Reversion'), ('swing', 'Swing Trading'), ('trend_following', 'Trend Following'), ('custom', 'Custom Strategy')], max_length=50, verbose_name='Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('inactive', 'Inactive'), ('testing', 'Testing/Paper')], default='inactive', max_length=20, verbose_name='Status')),
                ('config', models.JSONField(default=dict, verbose_name='Configuration')),
                ('watchlist', models.JSONField(default=list, verbose_name='Watchlist (Symbols)')),
                ('position_size_pct', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Position Size %')),
                ('max_positions', models.IntegerField(default=5, verbose_name='Max Open Positions')),
                ('max_daily_loss_pct', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='Max Daily Loss %')),
                ('entry_rules', models.JSONField(default=dict, verbose_name='Entry Rules')),
                ('exit_rules', models.JSONField(default=dict, verbose_name='Exit Rules')),
                ('total_trades', models.IntegerField(default=0, verbose_name='Total Trades')),
                ('winning_trades', models.IntegerField(default=0, verbose_name='Winning Trades')),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Win Rate %')),
                ('total_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total P&L')),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Sharpe Ratio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('activated_at', models.DateTimeField(blank=True, null=True, verbose_name='Last Activated')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to='portfolios.portfolio')),
            ],
            options={
                'verbose_name': 'Strategy',
                'verbose_name_plural': 'Strategies',
                'db_table': 'strategies',
                'ordering': ['-created_at'],
            },
        ),
    ]
