# Generated by Django 5.2.11 on 2026-03-02 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backtest',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backtests', to='strategies.strategy'),
        ),
        migrations.AddIndex(
            model_name='strategy',
            index=models.Index(fields=['user', '-created_at'], name='strategies_user_id_9ddeeb_idx'),
        ),
        migrations.AddIndex(
            model_name='strategy',
            index=models.Index(fields=['status'], name='strategies_status_de6fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='backtest',
            index=models.Index(fields=['strategy', '-created_at'], name='backtests_strateg_9107c4_idx'),
        ),
        migrations.AddIndex(
            model_name='backtest',
            index=models.Index(fields=['status'], name='backtests_status_3a6673_idx'),
        ),
    ]
