# Generated by Django 5.2.11 on 2026-03-04 12:39

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StrategyTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Template Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('momentum', 'Momentum'), ('mean_reversion', 'Mean Reversion'), ('swing', 'Swing Trading'), ('trend_following', 'Trend Following'), ('breakout', 'Breakout'), ('scalping', 'Scalping'), ('position', 'Position Trading')], max_length=50, verbose_name='Category')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20, verbose_name='Difficulty Level')),
                ('strategy_type', models.CharField(max_length=50, verbose_name='Strategy Type')),
                ('config', models.JSONField(default=dict, verbose_name='Configuration Template')),
                ('entry_rules', models.JSONField(default=dict, verbose_name='Entry Rules Template')),
                ('exit_rules', models.JSONField(default=dict, verbose_name='Exit Rules Template')),
                ('default_position_size_pct', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5, verbose_name='Default Position Size %')),
                ('default_max_positions', models.IntegerField(default=5, verbose_name='Default Max Positions')),
                ('default_max_daily_loss_pct', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5, verbose_name='Default Max Daily Loss %')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Usage Count')),
                ('tags', models.JSONField(default=list, verbose_name='Tags')),
                ('expected_win_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Expected Win Rate %')),
                ('expected_sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Expected Sharpe Ratio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Strategy Template',
                'verbose_name_plural': 'Strategy Templates',
                'db_table': 'strategy_templates',
                'ordering': ['-is_featured', '-usage_count', 'name'],
                'indexes': [models.Index(fields=['category'], name='strategy_te_categor_0d8d98_idx'), models.Index(fields=['difficulty'], name='strategy_te_difficu_ee2c26_idx'), models.Index(fields=['is_active', '-usage_count'], name='strategy_te_is_acti_c8de3f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Watchlist Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('symbols', models.JSONField(default=list, verbose_name='Symbols')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('color', models.CharField(default='blue', max_length=20, verbose_name='Color')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watchlist',
                'verbose_name_plural': 'Watchlists',
                'db_table': 'watchlists',
                'ordering': ['-is_default', 'name'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='watchlists_user_id_ba7d11_idx')],
            },
        ),
    ]
