# Generated by Django 5.2.11 on 2026-03-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False, verbose_name='Onboarding Completed'),
        ),
    ]
