# Generated by Django 5.2.11 on 2026-03-02 02:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20, verbose_name='Symbol')),
                ('decision', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('hold', 'Hold')], max_length=10, verbose_name='Decision')),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Confidence Score')),
                ('technical_analysis', models.JSONField(blank=True, null=True, verbose_name='Technical Analysis')),
                ('fundamental_analysis', models.JSONField(blank=True, null=True, verbose_name='Fundamental Analysis')),
                ('sentiment_analysis', models.JSONField(blank=True, null=True, verbose_name='Sentiment Analysis')),
                ('risk_assessment', models.JSONField(blank=True, null=True, verbose_name='Risk Assessment')),
                ('trade_signal', models.JSONField(blank=True, null=True, verbose_name='Trade Signal')),
                ('rationale', models.TextField(blank=True, verbose_name='Rationale')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Agent Decision',
                'verbose_name_plural': 'Agent Decisions',
                'db_table': 'agent_decisions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], max_length=20, verbose_name='Level')),
                ('message', models.TextField(verbose_name='Message')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Data')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Agent Log',
                'verbose_name_plural': 'Agent Logs',
                'db_table': 'agent_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbols', models.JSONField(default=list, verbose_name='Symbols Analyzed')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='Duration (seconds)')),
                ('signals_generated', models.IntegerField(default=0, verbose_name='Signals Generated')),
                ('errors', models.JSONField(blank=True, null=True, verbose_name='Errors')),
            ],
            options={
                'verbose_name': 'Agent Run',
                'verbose_name_plural': 'Agent Runs',
                'db_table': 'agent_runs',
                'ordering': ['-started_at'],
            },
        ),
    ]
