# Generated by Django 5.2.11 on 2026-03-02 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('strategies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentdecision',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='strategies.strategy'),
        ),
        migrations.AddField(
            model_name='agentlog',
            name='agent_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='agents.agentdecision'),
        ),
        migrations.AddField(
            model_name='agentrun',
            name='strategy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_runs', to='strategies.strategy'),
        ),
        migrations.AddField(
            model_name='agentlog',
            name='agent_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='agents.agentrun'),
        ),
        migrations.AddField(
            model_name='agentdecision',
            name='agent_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='agents.agentrun'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['strategy', '-started_at'], name='agent_runs_strateg_86d186_idx'),
        ),
        migrations.AddIndex(
            model_name='agentrun',
            index=models.Index(fields=['status'], name='agent_runs_status_c2c587_idx'),
        ),
        migrations.AddIndex(
            model_name='agentlog',
            index=models.Index(fields=['agent_run', '-created_at'], name='agent_logs_agent_r_df6a71_idx'),
        ),
        migrations.AddIndex(
            model_name='agentlog',
            index=models.Index(fields=['level'], name='agent_logs_level_adaaa3_idx'),
        ),
        migrations.AddIndex(
            model_name='agentdecision',
            index=models.Index(fields=['symbol', '-created_at'], name='agent_decis_symbol_c1f6af_idx'),
        ),
        migrations.AddIndex(
            model_name='agentdecision',
            index=models.Index(fields=['strategy', '-created_at'], name='agent_decis_strateg_d907ea_idx'),
        ),
    ]
