# Generated by Django 5.2.11 on 2026-03-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='agent',
            new_name='custom_agen_user_id_0eff6e_idx',
            old_name='custom_agen_user_id_5c2a2f_idx',
        ),
        migrations.RenameIndex(
            model_name='agent',
            new_name='custom_agen_is_acti_eaaf37_idx',
            old_name='custom_agen_is_acti_1e2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='agent',
            new_name='custom_agen_agent_t_c51746_idx',
            old_name='custom_agen_agent_t_4d5e6f_idx',
        ),
    ]
