# Generated by Django 5.2.11 on 2026-03-02 02:12

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Portfolio Name')),
                ('portfolio_type', models.CharField(choices=[('live', 'Live Trading'), ('paper', 'Paper Trading')], default='paper', max_length=20, verbose_name='Type')),
                ('initial_capital', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Initial Capital')),
                ('cash_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Cash Balance')),
                ('total_equity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total Equity')),
                ('daily_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Daily P&L')),
                ('total_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Total P&L')),
                ('total_pnl_pct', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10, verbose_name='Total P&L %')),
                ('total_trades', models.IntegerField(default=0, verbose_name='Total Trades')),
                ('winning_trades', models.IntegerField(default=0, verbose_name='Winning Trades')),
                ('losing_trades', models.IntegerField(default=0, verbose_name='Losing Trades')),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Win Rate %')),
                ('max_drawdown', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10, verbose_name='Max Drawdown %')),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Sharpe Ratio')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'db_table': 'portfolios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField(db_index=True, verbose_name='Snapshot Date')),
                ('total_equity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total Equity')),
                ('cash_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cash Balance')),
                ('positions_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Positions Value')),
                ('daily_pnl', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Daily P&L')),
                ('cumulative_pnl', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cumulative P&L')),
                ('total_trades', models.IntegerField(default=0, verbose_name='Total Trades')),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Win Rate %')),
                ('sharpe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Sharpe Ratio')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Portfolio Snapshot',
                'verbose_name_plural': 'Portfolio Snapshots',
                'db_table': 'portfolio_snapshots',
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20, verbose_name='Symbol')),
                ('side', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], default='long', max_length=10, verbose_name='Side')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('avg_entry_price', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Avg Entry Price')),
                ('current_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Current Price')),
                ('cost_basis', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Cost Basis')),
                ('current_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Current Value')),
                ('unrealized_pnl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Unrealized P&L')),
                ('unrealized_pnl_pct', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10, verbose_name='Unrealized P&L %')),
                ('stop_loss_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Stop Loss')),
                ('take_profit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Take Profit')),
                ('trailing_stop_enabled', models.BooleanField(default=False, verbose_name='Trailing Stop')),
                ('trailing_stop_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Trailing Stop %')),
                ('opened_at', models.DateTimeField(auto_now_add=True, verbose_name='Opened At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'db_table': 'positions',
                'ordering': ['-opened_at'],
            },
        ),
    ]
