# Generated by Django 5.2.11 on 2026-03-02 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolios', '0001_initial'),
        ('strategies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='portfoliosnapshot',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='position',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='portfolios.portfolio'),
        ),
        migrations.AddField(
            model_name='position',
            name='strategy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='strategies.strategy'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['user', '-created_at'], name='portfolios_user_id_c744e0_idx'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['portfolio_type', 'is_active'], name='portfolios_portfol_d02d23_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='portfoliosnapshot',
            index=models.Index(fields=['portfolio', '-snapshot_date'], name='portfolio_s_portfol_4f5098_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliosnapshot',
            unique_together={('portfolio', 'snapshot_date')},
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['portfolio', 'symbol'], name='positions_portfol_9f06b8_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['symbol', '-opened_at'], name='positions_symbol_5aa7e1_idx'),
        ),
    ]
