# Generated by Django 5.2.11 on 2026-03-02 02:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20, verbose_name='Symbol')),
                ('indicator_type', models.CharField(choices=[('rsi', 'RSI'), ('macd', 'MACD'), ('sma', 'Simple Moving Average'), ('ema', 'Exponential Moving Average'), ('bollinger', 'Bollinger Bands'), ('atr', 'Average True Range')], max_length=50, verbose_name='Indicator Type')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Timestamp')),
                ('value', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Value')),
                ('parameters', models.JSONField(default=dict, verbose_name='Parameters')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Indicator',
                'verbose_name_plural': 'Indicators',
                'db_table': 'market_indicators',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'indicator_type', '-timestamp'], name='market_indi_symbol_6a4058_idx')],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20, verbose_name='Symbol')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='Timestamp')),
                ('open', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Open')),
                ('high', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='High')),
                ('low', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Low')),
                ('close', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Close')),
                ('volume', models.BigIntegerField(verbose_name='Volume')),
                ('source', models.CharField(default='', max_length=50, verbose_name='Data Source')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Quote',
                'verbose_name_plural': 'Quotes',
                'db_table': 'market_quotes',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', '-timestamp'], name='market_quot_symbol_eb5762_idx'), models.Index(fields=['timestamp'], name='market_quot_timesta_ce6706_idx')],
                'unique_together': {('symbol', 'timestamp', 'source')},
            },
        ),
    ]
