# Generated by Django 5.2.11 on 2026-03-04 12:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockScreener',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Symbol')),
                ('name', models.CharField(max_length=255, verbose_name='Company Name')),
                ('price', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='Current Price')),
                ('change_pct', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Change %')),
                ('volume', models.BigIntegerField(blank=True, null=True, verbose_name='Volume')),
                ('avg_volume', models.BigIntegerField(blank=True, null=True, verbose_name='Avg Volume (30d)')),
                ('market_cap', models.BigIntegerField(blank=True, null=True, verbose_name='Market Cap')),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='P/E Ratio')),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Dividend Yield %')),
                ('rsi', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='RSI')),
                ('sma_50', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='SMA 50')),
                ('sma_200', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='SMA 200')),
                ('week_52_high', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='52 Week High')),
                ('week_52_low', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='52 Week Low')),
                ('sector', models.CharField(blank=True, max_length=100, verbose_name='Sector')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='Industry')),
                ('exchange', models.CharField(default='', max_length=50, verbose_name='Exchange')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Stock Screener Data',
                'verbose_name_plural': 'Stock Screener Data',
                'db_table': 'stock_screener',
                'ordering': ['symbol'],
                'indexes': [models.Index(fields=['symbol'], name='stock_scree_symbol_be4537_idx'), models.Index(fields=['sector'], name='stock_scree_sector_655f14_idx'), models.Index(fields=['industry'], name='stock_scree_industr_c3001a_idx'), models.Index(fields=['market_cap'], name='stock_scree_market__5c8c91_idx'), models.Index(fields=['volume'], name='stock_scree_volume_3ea41a_idx'), models.Index(fields=['rsi'], name='stock_scree_rsi_210448_idx')],
            },
        ),
    ]
