# Generated by Django 5.2.11 on 2026-03-05 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_watchlist'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='watchlist',
            new_name='market_watc_user_id_864a18_idx',
            old_name='market_watc_user_id_added_idx',
        ),
    ]
