# Generated by Django 5.2.11 on 2026-03-02 02:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('trade_executed', 'Trade Executed'), ('approval_required', 'Approval Required'), ('strategy_alert', 'Strategy Alert'), ('risk_alert', 'Risk Alert'), ('system', 'System')], max_length=50, verbose_name='Type')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Data')),
                ('send_email', models.BooleanField(default=False, verbose_name='Send Email')),
                ('send_push', models.BooleanField(default=True, verbose_name='Send Push')),
                ('send_sms', models.BooleanField(default=False, verbose_name='Send SMS')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
